### ISSUE TITLE
AmbiguousElementError is raised when locator matches multiple elements

### ISSUE THREAD

**Issue by dnovikau** [thefrontside/interactors#240] opened 2023-10-16 18:57 UTC
It would be more convenient if the first element that matches specified locator would return instead of raising AmbiguousElementError.

**Comment by cowboyd** [comment] 2023-10-16 19:19
@dnovikau This is actually by design. The guiding principle behind interactors is that they flow from the perspective of how the user would interact with a UI, and not code. 

This is, for example, why most of the locators match human readable text, and not test ids or data attributes.

While it might be more convenient for code, a user must, by definition be able to disambiguate between elements in order to use them correctly, and so having interactors which reflect that results, in our experience, a better structured UI.

All that said, what is your specific structure of HTML that is causing problems and would be made better by not raising ambiguous element errors?

**Comment by cowboyd** [comment] 2023-10-26 18:02
I'm going to close this, but leave this here. A common option to disambiguate elements is to use a filter https://frontside.com/interactors/docs/locators-filters#filters

**Closed by cowboyd** 2023-10-26 18:02 UTC
